### PR TITLE
Master Update

### PR DESCRIPTION
**Pull request by Justman10000**
### Added

- Repos for PHP and Node included note
- [Prism](https://prismjs.com) added
- Crowdin added for translations

### Changed

- Switched to darkmode

### Fixxed

- #7 and #13 included
- Minor fixes

### CODE REVIEW

**Comment by Justman10000** [comment]
@rwarasaurus

**Comment by rwarasaurus** [comment]
Screenshot from 2022-07-04 21-46-34

How many file changes! :joy:

**Comment by Justman10000** [comment]
> Screenshot from 2022-07-04 21-46-34
> 
> How many file changes! 😂

Yes 😅

**Comment by Justman10000** [comment]
@rwarasaurus

**Comment by Justman10000** [comment]
@rwarasaurus

**Comment by Justman10000** [comment]
@rwarasaurus

**Comment by Justman10000** [comment]
@rwarasaurus

**Comment by Justman10000** [comment]
@rwarasaurus

**Comment by Justman10000** [comment]
@rwarasaurus

**Comment by Justman10000** [comment]
@rwarasaurus

**Pull request closed without merging**
